FROM node:20.16.0-alpine as base

RUN addgroup app && adduser -S -G app app

USER app

WORKDIR /usr/src/app

COPY --chown=app:app package*json ./

RUN npm install

COPY --chown=app:app . /usr/src/app/

EXPOSE 5173

CMD ["npm", "run", "dev"]