FROM node:20.16.0-alpine as builder

RUN addgroup app && adduser -S -G app app

USER app

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY --chown=app:app . ./
RUN chown -R app:app /usr/src/app

EXPOSE 9000

CMD ["npm", "run", "dev"]