FROM node:20.16.0-alpine as base

RUN addgroup app && adduser -S -G app app

USER root

WORKDIR /usr/src/app

COPY --chown=app:app package*json ./

RUN npm install

RUN npm install nodemon

COPY --chown=app:app . /usr/src/app/

USER app

EXPOSE 9000

CMD [ "npm", "run", "dev"]